#!/usr/bin/env python3
"""Bundle the JSON curriculum into web/curriculum.js.

The web app must work when opened straight from disk (file://), where fetch()
of a local JSON file is blocked. So the data ships as a plain script that
assigns a global.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
OUT = os.path.join(ROOT, "web", "curriculum.js")

data = {}
for name in ("typing", "nvim", "python"):
    with open(os.path.join(ROOT, "curriculum", f"{name}.json"), encoding="utf-8") as fh:
        data[name] = json.load(fh)
with open(os.path.join(ROOT, "curriculum", "combos.json"), encoding="utf-8") as fh:
    data["combos"] = json.load(fh)

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("/* GENERATED by tools/build_web.py — edit curriculum/*.json instead. */\n")
    fh.write("window.CURRICULUM = ")
    json.dump(data, fh, ensure_ascii=False, separators=(",", ":"))
    fh.write(";\n")

size = os.path.getsize(OUT)
print(f"web/curriculum.js: {size / 1024:.0f} KB")
